site_name: 浙江大学2024-2025学年秋冬学期微积分（甲）I辅学
site_url: https://zjucalc24.github.io/
site_author: yuanhongyi2004

extra:
  social:
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/3546574332365752
    - icon: fontawesome/brands/github
      link: https://github.com/yuanhongyi/zjucalc24


theme: 
  name: material #主题
  logo: graph/ZJU-logo.svg
  favicon: graph/ZJU-logo.svg 
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
    repo: fontawesome/brands/github
    edit: material/pencil
  features:
    - search.highlight
#    - navigation.instant
    - navigation.expand
    - navigation.footer
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
#    - navigation.prune
    - navigation.indexes
    - navigation.top
    - header.autohide
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.tabs.link
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    code: JetBrains Mono
    text: Noto Serif SC


markdown_extensions:
  - admonition
  # Python Markdown
  - toc:
      permalink: true
      toc_depth: 3
  - abbr
  - def_list
  - attr_list
  - footnotes
  - md_in_html
  - admonition
  - sane_lists
  # Python Markdown Extensions
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - neoteroi.cards # install using `pip install neoteroi-mkdocs`

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://jsd.onmicrosoft.cn/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/neoteroi-mkdocs.css
  - stylesheets/custom.css

plugins:
  - search
  - glightbox # install using `pip install mkdocs-glightbox`
  - heti:
      extra_skipped_class:
        - arithmatex
      disable_serve: false
  - git-revision-date-localized
  - mkdocs-pdf
  # x- table-reader
  # - git-authors
  # - git-committers
  # x- with-pdf


nav:
  - Preface: 
    - Preface: index.md
  - Slides:
    - 微分中值定理:
      - 泰勒展开式: slides/diff/Taylor/slides_Taylor.md
      - 常数K值法: slides/diff/constK/slides_constK.md
    - 不定积分:
      - 积分表: slides/int/indefinite/table.md
      - 有理函数: slides/int/indefinite/1.md
      - 有理三角函数: slides/int/indefinite/2.md
      - 换元法和分部积分: slides/int/indefinite/3.md
    - 定积分:
      - 定积分基础: slides/int/definite/1.md
      # - 定积分其他: slides/int/definite/2.md
      # - 区间再现公式: slides/int/definite/3.md
    - 积分不等式:
      - 方法汇总: slides/int_ineq/all.md
      - 构造变限积分: slides/int_ineq/1.md
      - 利用中值定理: slides/int_ineq/2.md
  - Quiz:
    - 24数分H第二次小测: quiz/anal_quiz2.md
    - 24微甲小测(周三班): quiz/calc_quiz2_1.md
  - Exam:
    - 考情分析: exam/final_exam_analysis.md
    - 24微甲期末模拟: exam/24final_sim.md
    - 模拟题分析与解答: exam/report&ans.md
  - PDF: 
    - Index: pdf/index.md
    - 数列极限: pdf/seq_lim/1.md
    - 函数与导数(期中复习I): pdf/func_diff/1.md
    - 期中复习: pdf/midterm/1.md
    - 微分中值定理: pdf/diff_mean/1.md
    - 不定积分: pdf/indef_int/1.md
    - 定积分: pdf/def_int/1.md
    - 积分不等式: pdf/int_ineq/1.md
    - 反常积分: pdf/imp_int/1.md
  - Misc:
    - Index: misc/index.md
    - 23H.8定积分对称性: misc/20241205.md
    - 习题6.51两种解法: misc/20241209.md
    - 23J.15积分不等式: misc/20241210.md
    - 21J.12积分不等式: misc/20241211.md
    - 敛迫性+定积分定义: misc/20241212.md
    - 18J.13Young不等式: misc/20241213.md
    - 22H.15Dunkel不等式: misc/20241214.md
    - 22H.16微分中值定理: misc/20241215.md
    - 18H.12凸函数连续性: misc/20241216.md
    - 具体函数的中值极限: misc/20241217.md
    - 积分的极限1: misc/20241218.md
    - 20J.4积分的极限2: misc/20241219.md